apiVersion: v1
kind: Service
metadata:
  name: aspdotnetapp-svc
spec:
  type: LoadBalancer
  selector:
    app: aspdotnetapp
  ports:
    - name: aspdotnetapp
      protocol: TCP
      port: 8080
      targetPort: 8080
