stages:
 - stage: BuildDocker
   displayName: Build & Push Docker Image 
   jobs: 
   - job: BuildDocker
     displayName: Build & Push Docker Image
     steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: ${{ parameters.acrRepoName }}
          dockerfile: '$(System.DefaultWorkingDirectory)/aspnetapp/Dockerfile'
          containerRegistry: $(dockerServiceConnection)
          tags: |
            latest
            